### ISSUE TITLE
link.ld isn't a valid linker script

### ISSUE THREAD

**Issue by Avidanborisov** [littleosbook/littleosbook#10]
The sections have to be placed inside a `SECTIONS` block, otherwise `ld` outputs a syntax error.

    ld:link.ld:5: syntax error

The following linker script works:

    ENTRY(loader)

    SECTIONS {
        . = 1M;

        .text : ALIGN(4K) {
            *(.text)
        }

        .rodata : ALIGN(4K) {
            *(.rodata)
        }

        .data : ALIGN(4K) {
            *(.data)
        }

        .bss : ALIGN(4K) {
            *(COMMON)
            *(.bss)
        }
    }

**Comment by sinistersnare** [comment]
Ill submit a PR for this :D

**Comment by olalonde** [comment]
:+1: the loader script in the book didn't work for me either. @Avidanborisov 's version worked though.

```ld
ENTRY(loader)

SECTIONS {
  . = 1M;               /* the code should be loaded at 1 MB */

  .text : ALIGN (4K)    /* align at 4 KB */
  {
    *(.text)            /* all text sections from all files */
  }

  .rodata : ALIGN (4K)  /* align at 4 KB */
  {
    *(.rodata)          /* all read-only data sections from all files */
  }

  .data : ALIGN (4K)    /* align at 4 KB */
  {
    *(.data)            /* all data sections from all files */
  }

  .bss : ALIGN (4K)     /* align at 4 KB */
  {
    *(COMMON)           /* all COMMON sections from all files */
    *(.bss)             /* all bss sections from all files */
  }
}
```
