### ISSUE TITLE
Bochs is broken in Ubuntu

### ISSUE THREAD

**Issue by samwise** [littleosbook/littleosbook#20]
Not a problem with the book itself but perhaps worth a mention.     

    $ bochs -f bochsrc.txt -q
    ...
    bochs-bin: symbol lookup error: /usr/lib/bochs/plugins/libbx_x.so: undefined symbol: XpmCreatePixmapFromData

This can be addressed with:

    $ LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libXpm.so bochs -f bochsrc.txt -q

**Comment by Avidanborisov** [comment]
Another option is using

    display_library: sdl

in `bochsrc.txt`.

**Comment by helino** [comment]
@Avidanborisov yeah, that is the fix I just tried out locally, worked great (and then there is no need to explain LD_PRELOAD). Do you want to submit a PR?

**Comment by Avidanborisov** [comment]
@helino Sure, see #26

**Comment by helino** [comment]
:+1:
