### ISSUE TITLE
ld linker script syntax possibly wrong

### ISSUE THREAD

**Issue by Metaluim** [littleosbook/littleosbook#32]
Hi,

I'm using GNU ld v2.22 and I couldn't use the linker script provided in section 2.3.2.
I had to use a semicolon on the starting address statement, had to use colons to define the sections and had to wrap them in a SECTIONS area. I don't know if this is due to having an older version of ld but I simply couldn't run the script without these changes.
Here's the full script:

```Assembly
ENTRY(loader)

. = 0x00100000;

SECTIONS
{
.text ALIGN (0x1000):
{
    *(.text)
}
.rodata ALIGN (0x1000):
{
    *(.rodata*)
}
.data ALIGN (0x1000):
{
    *(.data)
}
.bss ALIGN (0x1000):
{
    *(COMMON)
    *(.bss)
}
}
```

**Comment by dannyvai** [comment]
https://github.com/littleosbook/littleosbook/issues/10

**Comment by Phlosioneer** [comment]
Seconded, independently came to the same file.

**Comment by Metaluim** [comment]
Apparently this is already being worked on, as evidenced by dannyvai. Closing the issue.
