### ISSUE TITLE
Can't locate 00000000CAFEBABE in the bochs log.

### ISSUE THREAD

**Issue by sejr** [littleosbook/littleosbook#36]
I attempted to write everything out on my own, which didn't work, so I proceeded to copy in the code directly from the book. I am still unable to locate this value, and would like to remedy this before continuing with the book.

[Our project is located here.](https://ide.c9.io/sejr/opensooose)

**Comment by aedrax** [comment]
For anyone looking at this in the future, we had to change our display_library to term, first we installed it with "sudo apt-get install bochs-term"

**Comment by polycopter** [comment]
I tried the change from sdl to term, but still no CAFE (or cafe)... EAX=00000000
