### ISSUE TITLE
Can't initialize memory in bss

### ISSUE THREAD

**Issue by BobbyRaduloff** [littleosbook/littleosbook#72]
When I try to compile the following code which I took directly from the book: 

>   global loader
> 
>  MAGIC_NUMBER equ 0x1BADB002
>  FLAGS        equ 0x0
>  CHECKSUM     equ -MAGIC_NUMBER
> 
>  section .text:
>  align 4
>    dd MAGIC_NUMBER
>    dd FLAGS
>    dd CHECKSUM
> 
>  loader:
>    mov eax, 0xCAFEBABE
>  .loop:
>    jmp .loop
> 
>  KERNEL_STACK_SIZE equ 4096
> 
>  section .bss
>  align 4
>  kernel_stack:
>    resb KERNEL_STACK_SIZE
>    mov esp, kernel_stack + KERNEL_STACK_SIZE

I get a weird error from NASM: "loader.s:24: warning: attempt to initialize memory in BSS section `.bss': ignored". Anyone have any idea what this is?

**Comment by BobbyRaduloff** [comment]
Figured it out myself. You cant put instructions (mov esp, kernel_stack + KERNEL_STACK_SIZE) in bss

**Comment by AdamOnAir** [comment]
> Figured it out myself. You cant put instructions (mov esp, kernel_stack + KERNEL_STACK_SIZE) in bss

Fixed code
