### ISSUE TITLE
bochs running but no print CAFEBABE

### ISSUE THREAD

**Issue by dodng** [littleosbook/littleosbook#84]
hi,

  I follow the instruction of Chapter 2,in the last step,run "bochs -f bochsrc.txt -q",
but  bochslog.txt  not  print  RAX=00000000CAFEBABE or EAX=CAFEBABE.

My  environment is   Ubuntu 14.04.3 LTS   
                                  EC2(aws)

**Comment by kithrak** [comment]
type c

**Comment by crclark96** [comment]
More detailed help in issue #53, I issued a pull request that has updated text here:
https://github.com/littleosbook/littleosbook/pull/80

**Comment by dodng** [comment]
thanks，I already can run it in my computer(graphic interface)
